version: '3'
services:
  db: 
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  odoo11:
    image: odoo:11.0
    depends_on:
      - db
    ports:
      - "8070:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo

volumes:
  odoo-web-data:
  odoo-db-data:
